vault_install_dir: /opt/vault
vault_relation_dirs:
  - "{{ vault_install_dir}}/ssl"
  - "{{ vault_install_dir}}/unseal_keys"
  - "{{ vault_install_dir}}/tokens"
vault_install_prerequisites:
  - git
  - unzip
vault_version: 1.10.0
vault_user: vault
vault_group: vault
vault_checksum: sha256:ec06473d79e77c05700f051278c54b0f7b6f2df64f57f630a0690306323f1175
vault_storage_type: file
vault_access_key: ''
vault_secret_key: ''
vault_bucket: ''
vault_tls_cert_file: "{{ vault_install_dir}}/ssl/cert.pem"
vault_tls_key_file: "{{ vault_install_dir}}/ssl/key.pem"
unseal_keys_dir_output: "{{ vault_install_dir}}/unseal_keys/"
root_token_dir_output: "{{ vault_install_dir}}/tokens/"
