vault_install_dir: /opt/vault
vault_relation_dirs:
  - "{{ vault_install_dir}}/ssl"
  - "{{ vault_install_dir}}/unseal_keys"
  - "{{ vault_install_dir}}/tokens"
vault_install_prerequisites:
  - libselinux-python
  - git
  - unzip
  - pyOpenSSL
vault_version: 1.8.2
vault_user: vault
vault_group: vault
vault_checksum: sha256:d74724d6cc22bf1e1c7c519009b0176809acf6f1c20ee56107de0cab54cd8463
vault_storage_type: file
vault_access_key: ''
vault_secret_key: ''
vault_bucket: ''
vault_tls_cert_file: "{{ vault_install_dir}}/ssl/cert.pem"
vault_tls_key_file: "{{ vault_install_dir}}/ssl/key.pem"
unseal_keys_dir_output: "{{ vault_install_dir}}/unseal_keys/"
root_token_dir_output: "{{ vault_install_dir}}/tokens/"
