- name: Add openresty repository
  get_url:
    url: https://openresty.org/package/centos/openresty.repo
    dest: /etc/yum.repos.d/openresty.repo
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"
  owner: root
  mode: 0644
  become: yes

- name: install openresty
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - openresty
    # - openresty-resty
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"
  become: yes
