---
- name: make sure relation service is running
  systemd:
    state: started
    name: "{{ item }}"
  loop:
    - strongswan
    - xl2tpd
  become: yes

- name: start strongswan
  shell: /usr/sbin/strongswan up "{{ VPN_CONNECTION_NAME }}"
  when: L2TP_STATUS == "enable"
  become: yes

- name: start ppp0
  shell: echo "c {{ VPN_CONNECTION_NAME }}" | tee -a /var/run/xl2tpd/l2tp-control > /dev/null
  when: L2TP_STATUS == "enable"
  become: yes

- name: Sleep for 9 seconds and continue with play
  wait_for:
    timeout: 9

- name: add route
  shell: ip route add {{ VPN_SUBNET }}/{{ VPN_MASK }} via {{ VPN_GATEWAY }}
  when: L2TP_STATUS == "enable"
  become: yes
  ignore_errors: yes

- name: stop the L2TP connection
  shell: echo "d {{ VPN_CONNECTION_NAME }}" | tee -a /var/run/xl2tpd/l2tp-control > /dev/null
  when: L2TP_STATUS == "disable"
  become: yes

- name: stop strongswan
  shell: /usr/sbin/strongswan down "{{ VPN_CONNECTION_NAME }}"
  when: L2TP_STATUS == "disable"
  become: yes

- name: delete route
  shell: /usr/sbin/ip route del {{ VPN_SUBNET }}/{{ VPN_MASK }}
  when: L2TP_STATUS == "disable"
  become: yes
  ignore_errors: yes

- name: show IP link and route information
  shell: |
    /usr/sbin/ip route show

- name: test L2TP connection
  shell: "ping -c 4 {{ VPN_GATEWAY }}"
  ignore_errors: true
  when: L2TP_STATUS == "enable"
