---
- name: Make sure relation service is running
  systemd:
    state: started
    name: "{{ item }}"
  loop:
    - strongswan
    - xl2tpd
  become: yes

- name: start the L2TP connection
  shell: |
    strongswan up "{{ VPN_CONNECTION_NAME }}" &&
    echo "c {{ VPN_CONNECTION_NAME }}" > /var/run/xl2tpd/l2tp-control &&
    ip route add {{ VPN_SUBNET }}/{{ VPN_MASK }} via {{ VPN_GATEWAY }} dev ppp0
  when:  L2TP_STATUS == "enable"
  become: yes

- name: stop the L2TP connection
  shell: |
    echo "d {{ VPN_CONNECTION_NAME }}" > /var/run/xl2tpd/l2tp-control &&
    strongswan down "{{ VPN_CONNECTION_NAME }}"
    ip route del {{ VPN_SUBNET }}/{{ VPN_MASK }}
  when: L2TP_STATUS == "disable"
  become: yes
