---
- name: Make sure relation service is running
  systemd:
    state: started
    name: "{{ item }}"
  loop:
    - strongswan
    - xl2tpd
  become: yes

- name: start the L2TP connection
  shell: |
    /usr/sbin/strongswan up "{{ VPN_CONNECTION_NAME }}"
    echo "c {{ VPN_CONNECTION_NAME }}" > /var/run/xl2tpd/l2tp-control
    ip route add {{ VPN_SUBNET }}/{{ VPN_MASK }} via {{ VPN_GATEWAY }} dev {{ VPN_DEV }}
  when:  L2TP_STATUS == "enable"
  become: yes
  notify:
    - test L2TP connection
    - show IP link and route information

- name: stop the L2TP connection
  shell: |
    echo "d {{ VPN_CONNECTION_NAME }}" > /var/run/xl2tpd/l2tp-control
    /usr/sbin/strongswan down "{{ VPN_CONNECTION_NAME }}"
    ip route del {{ VPN_SUBNET }}/{{ VPN_MASK }}
  when: L2TP_STATUS == "disable"
  become: yes
