---
- name: Install EPEL
  package:
    name: "{{ epel_package_name }}"
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: Install relation packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - strongswan
    - xl2tpd
    - ppp

