---
- name: get indices list
  uri:
    url: http://localhost:9200/_cat/indices?v&h=index&format=json
    method: GET
    return_content: yes
    timeout: 15
  register: index_list_result

- name: print indices list result
  debug:
    var: "{{ index_list_result | json_query(jquery) }}"
  when: index_list_result.status == 200
  vars:
    jquery: "content.*.index"

