---
- name: get indices list
  uri:
    url: http://localhost:9200/_cat/indices?h=index
    method: GET
    return_content: yes
    timeout: 15
  register: index_list_result

- name: print indices list result
  debug: 
    msg: "{{ index_list_result.content.splitlines() }}"
  when: index_list_result.status == 200
