---
- name: choice one random es server
  set_fact: random_host="{{ groups.all | random }}"

- name: get indices list
  uri:
    url: http://localhost:9200/_cat/indices?h=index
    method: GET
    return_content: yes
    timeout: 15
  register: index_list_result
  when: inventory_hostname == random_host

- name: print indices list result
  debug: 
    msg: "{{ index_list_result.content.splitlines() }}"
  when: index_list_result.status == 200
