- name: Ensure that free space on the tested volume is greater than 65%
  assert:
    that:
      - mount.size_available > mount.size_total|float * 0.65
    msg: Disk space has reached 35% threshold
  vars:
    mount: "{{ ansible_mounts | selectattr('mount','equalto',item.mount) | list | first }}"
  with_items:
    - "{{ ansible_mounts }}"